language: node_js

node_js:
  - '8.17'
  - '10.23'
  - '12.19'
  - '14.15'

install:
  - travis_retry npm install

script:
  - npm run build

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
